services:
  postgres_sorteador_db:
    image: postgres
    container_name: postgres_sorteador_db
    restart: always
    ports:
      - 80:5432
    env_file:
      - .env
    volumes: 
      - pg_sorteador-db:/var/lib/postgresql/data

  node_sorteador_app:
    container_name: node_sorteador_app
    build: .
    ports:
      - 80:5000
    depends_on:
      - postgres_sorteador_db
    env_file:
      - .env

volumes:
  pg_sorteador-db: